#!/usr/bin/python -u
# Copyright (c) 2019 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Run LOD command
"""
from pylond import lod

if __name__ == "__main__":
    lod.main()
