#!/usr/bin/python2 -u
# Copyright (c) 2019 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Run LOND commands
"""
from pylond import lond

if __name__ == "__main__":
    lond.main()
