/*
 * Copyright (c) 2019, DDN Storage Corporation.
 */
/*
 *
 * Generate the definition for Python library
 *
 * Author: Li Xi <lixi@ddn.com>
 */
#include <unistd.h>
#include <getopt.h>
#include <string.h>
#include "debug.h"
#include "definition.h"

static void usage(char *prog)
{
	fprintf(stderr,
		"Usage: %s <path-to-definition.py>\n",
		prog);
}

static void declare_command_options(FILE *fp,
				    struct command_options *command_options)
{
	char *has_arg;
	char *short_opt;
	char buffer[1024];
	const char *name = command_options->co_name;
	struct option *option = command_options->co_options;
	struct command_argument *argument = command_options->co_arguments;

	LINFO("declaring options for command [%s]\n", name);
	fprintf(fp, "%s = definition_helper.CommandOptions()\n", name);
	while (option->name != NULL) {
		/* hide the option */
		if (option->val == OPT_PROGNAME) {
			option++;
			continue;
		}
		LINFO("adding option [%s] of [%s]\n", option->name, name);

		if ((option->val >= 'a' && option->val <= 'x') ||
		    (option->val >= 'A' && option->val <= 'X')) {
			buffer[0] = '\'';
			buffer[1] = '-';
			buffer[2] = option->val;
			buffer[3] = '\'';
			buffer[4] = '\0';
			short_opt = buffer;
		} else {
			short_opt = "None";
		}
		if (option->has_arg)
			has_arg = "True";
		else
			has_arg = "False";
		fprintf(fp,
			"OPTION = definition_helper.CommandOption('--%s', %s, short_opt=%s)\n",
			option->name, has_arg, short_opt);
		fprintf(fp, "%s.cos_add_option(OPTION)\n", name);
		option++;
	}

	while (strcmp(argument->ca_type, ARG_TYPE_NONE) != 0) {
		LINFO("adding argument type [%s] to [%s]\n",
		      argument->ca_type, name);
		fprintf(fp, "%s.cos_add_argument(CARG(CARG.%s))\n", name,
			argument->ca_type);
		argument++;
	}
}

int main(int argc, char **argv)
{
	FILE *fp;
	char *path;
	struct command_options all_commands[] = ALL_COMMANDS;
	struct command_options *command_options;
	const char *head = ("# Please DO NOT edit this file directly!\n"
			    "# File generated by generate_definition command\n"
			    "# Copyright (c) 2019 DataDirect Networks, Inc.\n"
			    "# All Rights Reserved.\n"
			    "# Author: lixi@ddn.com\n"
			    "\n"
			    "\"\"\"\n"
			    "Constants that should be synced with C language codes\n"
			    "\"\"\"\n\n"
			    "from pylond import definition_helper\n\n");

	if (argc != 2) {
		usage(argv[0]);
		return 1;
	}

	path = argv[1];

	fp = fopen(path, "w");
	if (fp == NULL) {
		LERROR("failed to open file [%s]\n", path);
		return -1;
	}

	fprintf(fp, "%s", head);
	fprintf(fp, "CARG = definition_helper.CommandArgument\n");

	command_options = all_commands;
	while (command_options < all_commands + ARRAY_SIZE(all_commands)) {
		declare_command_options(fp, command_options);
		command_options++;
	}

	fprintf(fp, "LOND_OPTION_PROGNAME = '%s'\n", LOND_OPTION_PROGNAME);
	fclose(fp);

	return 0;
}
